### PR TITLE
ic2par.h revision fix

### PR DESCRIPTION
**Pull request by ChrisAndre**
This one compiles and functions properly - I tested the python wrapper with some sample data and it comes out identical.

The type passed for the template wouldn't work if the type could not be instantiated with an array initializer, however, but it doesn't appear that there are any use cases in the project that would cause this problem (so far).

My apologies for the last PR. I didn't have a build system running yet - that's embarrassing. In the future, would you like any small revisions or added documentation if I come across an opportunity?

### CODE REVIEW

**Comment by darioizzo** [comment]
Before I review your code, can you solve all warning issues?

You can check the Travis VM here : https://travis-ci.org/esa/pykep/builds/54409969

**Comment by ChrisAndre** [comment]
I wasn't able to reproduce those warnings on my own machine, so I looked it up and it appears that it those warnings are caused by a bug in gcc that has recently been fixed. I don't know much about Travis CI; would it be possible to patch gcc on the build server?

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53119

**Comment by darioizzo** [comment]
Done, can you please merge master and trigger the Travis build again?

**Comment by ChrisAndre** [comment]
It passes without any warnings now from gcc (as far as I have seen).

**Comment by darioizzo** [comment]
Indeed, thanks a lot :) Will review this and merge it to master when I have a bit of time ...... !!

**Comment by darioizzo** [comment]
Chris, what is this last commit? "GTOC build option attempt". It ended up in this pull request, please remove otherwise I cannot merge the rest.

FYI, the whole planet object chain has been overhauled and is now very different, so no more planet_ss and the like .... there is a dedicated module and namespace. In any case I did not understand what you were trying to do with this last commit ...

**Comment by ChrisAndre** [comment]
Ah yes, I did not mean to push that into this PR. It was meant to make the GTOC asteroids optional in the build, but that was for before the overhaul. I'll remove it ASAP.

**Pull request closed without merging**
