### PR TITLE
Adding linter tests to continuous integration in Pykep

### PR DESCRIPTION
**Pull request by pabloem**
Issue #134 would be caught by a linter. It may be a good idea to implement lint checks for pykep. What do you think @darioizzo ?

This PR adds an extra build type which runs lint checks (and currently fails). A healthy lint check could keep those failures out.

This PR is a work in progress for now.

### CODE REVIEW

**Comment by darioizzo** [comment]
Thanks for this PR, I think its a great addition to have a linting build ... hopefully you will manage to have it green 👍

**Comment by pabloem** [comment]
sure, I can make it green, and then mark it ready to review.

**Comment by pabloem** [comment]
@darioizzo this is ready for review.

As you see, I worked with @albertoibm on this change. The commit messages are self-descriptive. Let us know if this can be merged.

A reasonable question to ask is whether we need a new workflow for lint, or if we should just run lint on every python-3x test

**Comment by pabloem** [comment]
hi @darioizzo - did you have a chance to take a look? Most changes should be full-positives. Only special questions I expect are related to installing dependencies.

**Comment by darioizzo** [comment]
Had a look its fine as is. I am merging this for the upcoming release.

I saw the dependencies added to PyPi, sure they provide a better pykep experience.

Thanks for the PR!!! Keep 'em coming :)

**Pull request merged**
