### PR TITLE
New planet polymorphic structure

### PR DESCRIPTION
**Pull request by darioizzo**
The upcoming version of PyKEP will use a new namespace planets. In there is a new base class and all objects deriving from it, reimplement the ephemerides calculations. Planets with purely Keplerian eph derive from planets::keplerian, which in turns derives from planets::base.

This new structure will, for some time, coexist the old one for back compatibility purposes. The old classes are, though to be considered deprecated.

It will be possible to build python classes deriving from planets::base and thus re-implement the ephemerides computations in python.

This pull request is to allow some discussion before we actually dive into this.

### CODE REVIEW

**Comment by darioizzo** [comment]
IMPORTANT: This breakes back-compatibility with PyKEP 1.2.1

**Comment by Juanlu001** [comment]
If this code breaks backwards compatibility, did you consider making a 1.3 or even a 2.0 release to make cristal clear that an upgrade will lead to broken code? If I see a 1.2.2 I would assume only bug fixes have been made.

http://semver.org/

**Comment by darioizzo** [comment]
The actual number for the next release will be decided when we actually release. The current 1.1.2dev is the development code and we do not update the number during development it if big changes occur. 

You are right, though, when we actually will release the next version (September-October) we will probably release a 1.3.0 as the overhaul of planet objects is a rather big structural change and breaks the old code.

**Comment by darioizzo** [comment]
We could update the __version__ dictionary to make this clear adding a 'dev' field ...

**Comment by darioizzo** [comment]
We could also follow the indications in http://semver.org/, they seem reasonable ....

**Comment by venku122** [comment]
@darioizzo Would you happen to have a guide for converting old projects off of project_ss? I am working on reviving an old project, and I'd like to double check if the resource exists, before I dive into this and other PRs to figure out the conversions needed.

**Comment by darioizzo** [comment]
This old PR did not change any of the functionalities (resourcers) of the previous pygmo, it only added a new syntax and developed some new types of eph.

If you were using the planet_ss object of the previous pykep, in this new version `planet.jpl_lp` is the equivalent.

**Pull request merged**
